#!/bin/sh
#
# Startup file for WoT mud v0.1a
# Written by: Gary McNickle
#
# Note: I know next to nothing about writing shell scripts, SO, as
# soon as I get a chance to learn, I'll write a real startup script...
#

_mud="../src/wot"
_port=5000
_logdir="../data/logs"
_shutdown="../data/logs/shutdown.dat"
_email="gary@tarmongaidon.org"
_subject="Corefile"

if [ -e $_shutdown ]; then
  rm $_shutdown
fi

while [ ! -e $_shutdown ]; do
  _logfile=$(date +%j%H%M)

  _cmdline="$_mud $_port >& $_logdir/$_logfile"

   $_mud $_port > $_logdir/$_logfile 2>&1

  if [ -e core ]; then
    gdb -batch $_mud core | mail -s $_subject $_email
    mv core core.$_logfile
  fi

  sleep 15;
done

